### ISSUE TITLE
Unable to re-authenticate user after timeout.

### ISSUE THREAD

**Issue by bsiara** [klinux/gocd-keycloak-oauth-authorization-plugin#1]
I login to gocd using keycloak, after about 5 min I get error in ui:
`Unable to re-authenticate user after timeout.`
and in logs:
```jvm 1    | 2021-09-15 12:28:08,364 ERROR [qtp45115720-8895655] p.c.g.a.k.c.g.a.k.KeycloakPlugin:127 [plugin-cd.go.authorization.keycloak] - Error while executing request go.cd.authorization.authenticate-user
jvm 1    | java.lang.RuntimeException: Api call to `/auth/realms/myrealm/protocol/openid-connect/userinfo` failed with error: `{"error":"invalid_token","error_description":"Token verification failed"}`
jvm 1    | 	at cd.go.authorization.keycloak.KeycloakApiClient.executeRequest(KeycloakApiClient.java:148)
jvm 1    | 	at cd.go.authorization.keycloak.KeycloakApiClient.userProfile(KeycloakApiClient.java:135)
jvm 1    | 	at cd.go.authorization.keycloak.executors.UserAuthenticationRequestExecutor.execute(UserAuthenticationRequestExecutor.java:59)
jvm 1    | 	at cd.go.authorization.keycloak.requests.Request.execute(Request.java:47)
jvm 1    | 	at cd.go.authorization.keycloak.KeycloakPlugin.handle(KeycloakPlugin.java:71)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:134)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:208)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:164)
jvm 1    | 	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:131)
jvm 1    | 	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:49)
jvm 1    | 	at com.thoughtworks.go.plugin.access.authorization.AuthorizationExtension.authenticateUser(AuthorizationExtension.java:260)
jvm 1    | 	at com.thoughtworks.go.server.newsecurity.providers.WebBasedPluginAuthenticationProvider.authenticateWithExtension(WebBasedPluginAuthenticationProvider.java:80)
jvm 1    | 	at com.thoughtworks.go.server.newsecurity.providers.WebBasedPluginAuthenticationProvider.authenticateWithExtension(WebBasedPluginAuthenticationProvider.java:41)
jvm 1    | 	at com.thoughtworks.go.server.newsecurity.providers.AbstractPluginAuthenticationProvider.authenticateUser(AbstractPluginAuthenticationProvider.java:118)
jvm 1    | 	at com.thoughtworks.go.server.newsecurity.providers.AbstractPluginAuthenticationProvider.reauthenticate(AbstractPluginAuthenticationProvider.java:65)
jvm 1    | 	at com.thoughtworks.go.server.newsecurity.filters.AbstractReAuthenticationFilter.attemptAuthentication(AbstractReAuthenticationFilter.java:120)
jvm 1    | 	at com.thoughtworks.go.server.newsecurity.filters.AbstractReAuthenticationFilter.performReauthentication(AbstractReAuthenticationFilter.java:89)
jvm 1    | 	at com.thoughtworks.go.server.newsecurity.filters.AbstractReAuthenticationFilter.doFilterInternal(AbstractReAuthenticationFilter.java:76)
jvm 1    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
jvm 1    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
jvm 1    | 	at com.thoughtworks.go.server.newsecurity.filters.InvalidateAuthenticationOnSecurityConfigChangeFilter.doFilterInternal(InvalidateAuthenticationOnSecurityConfigChangeFilter.java:105)
jvm 1    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
jvm 1    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
jvm 1    | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
jvm 1    | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
jvm 1    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
jvm 1    | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:208)
jvm 1    | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
jvm 1    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
jvm 1    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
jvm 1    | 	at com.thoughtworks.go.server.newsecurity.filters.AlwaysCreateSessionFilter.doFilterInternal(AlwaysCreateSessionFilter.java:40)
jvm 1    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
jvm 1    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
jvm 1    | 	at com.thoughtworks.go.server.newsecurity.filters.AbstractSessionReduceIdleTimeoutFilter.doFilterInternal(AbstractSessionReduceIdleTimeoutFilter.java:44)
jvm 1    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
jvm 1    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
jvm 1    | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
jvm 1    | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:185)
jvm 1    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
jvm 1    | 	at com.thoughtworks.go.server.newsecurity.filters.ModeAwareFilter.doFilter(ModeAwareFilter.java:79)
jvm 1    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
jvm 1    | 	at com.thoughtworks.go.server.web.BackupFilter.doFilterInternal(BackupFilter.java:79)
jvm 1    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
jvm 1    | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
jvm 1    | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
jvm 1    | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
jvm 1    | 	at com.thoughtworks.go.server.newsecurity.filterchains.MainFilterChain.doFilter(MainFilterChain.java:79)
jvm 1    | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
jvm 1    | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
jvm 1    | 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
jvm 1    | 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
jvm 1    | 	at com.thoughtworks.go.server.web.DefaultHeadersFilter.doFilter(DefaultHeadersFilter.java:51)
jvm 1    | 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201)
jvm 1    | 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
jvm 1    | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
jvm 1    | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
jvm 1    | 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:766)
jvm 1    | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
jvm 1    | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
jvm 1    | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
jvm 1    | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
jvm 1    | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
jvm 1    | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
jvm 1    | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
jvm 1    | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
jvm 1    | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
jvm 1    | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
jvm 1    | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
jvm 1    | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
jvm 1    | 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)
jvm 1    | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
jvm 1    | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
jvm 1    | 	at org.eclipse.jetty.server.Server.handle(Server.java:516)
jvm 1    | 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
jvm 1    | 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
jvm 1    | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
jvm 1    | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
jvm 1    | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
jvm 1    | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
jvm 1    | 	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
jvm 1    | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
jvm 1    | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
jvm 1    | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
jvm 1    | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
jvm 1    | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
jvm 1    | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
jvm 1    | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
jvm 1    | 	at java.base/java.lang.Thread.run(Unknown Source)```
and I need to login again to gocd.
gocd version: 21.2.0
plugin version: 1.0.3-7

**Comment by klinux** [comment]
Hi, can you check the lifetime of you token in Keycloak configuration?

The stack that you post, the error let me think that **Keycloak** is denying access in **userinfo** endpoint.

Another configuration that you need to check, is the session time in gocd configuration, sometime you need to increase the idle timeout:

```
go.security.reauthentication.interval
```
https://docs.gocd.org/current/configuration/dev_authentication.html#configurable-properties

This configuration by default needs to be re-authenticate after 30 minutes

Thank you

**Comment by bsiara** [comment]
Increase Access Token Lifespan is a resolution to this topic. Thanks
